### ISSUE TITLE
Help on how to use!

### ISSUE THREAD

**Issue by saldous** [nrbrook/NBUIKitMainThreadGuard#2]
Sorry, I'm new to this. How do I do this?

"Add a preprocessor macro in build settings for the debug build: DEBUG=1 and in Other Swift Flags: -DDEBUG"

**Comment by tache** [comment]
In your Target's Build Settings, 
search for Preprocessor Macros, in the row for Debug, under your Target's column, enter DEBUG=1
search for Other Swift Flags, in the row for Other Swift Flags, under your Target's column, enter -DDEBUG

**Comment by nrbrook** [comment]
See https://github.com/nrbrook/NBUIKitMainThreadGuard/commit/35f9d34933649f204086c96fbef1b6c81f67dc05
