### ISSUE TITLE
swift 3.1 deprecates initialize()

### ISSUE THREAD

**Issue by jonasman** [nrbrook/NBUIKitMainThreadGuard#3]
any ideas on how to fix?

**Comment by nrbrook** [comment]
Fixed with 4535068d6cfbbdaac1e1ca3e096fca0009ef6bc5. As far as I can tell, AppDelegate init is the earliest user code can be executed. initialize still seems to work though, so this is just future proofing. If you can't compile with initialize, just remove it and please submit a PR.
