### ISSUE TITLE
Silence warning about initialize() from Swift 3.1

### ISSUE THREAD

**Issue by mime29** [nrbrook/NBUIKitMainThreadGuard#4]
> NBUIKitMainThreadGuard.swift:19:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

Here is the message that you get after compiling with Swift 3.1.
Is there a way to either find a better technique to achieve the same thing or simply to silence this warning without changing compilation settings?

**Comment by nrbrook** [comment]
I have added the branch https://github.com/nrbrook/NBUIKitMainThreadGuard/tree/initialize-removed for now
